<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="main" style="margin-top: 40px">
    <section class="content">
        <div class="text-center">
            <p class="mb-5 fs-4">Извините, но у вас недостаточно прав для доступа к ресурсу</p>
            <a class="btn btn-success" href="/">Вернуться на главную</a>
        </div>
    </section>
</div>
</body>
</html>